"""Password file management for the opencode server.

The password is generated by `nina init` and stored in a separate file
inside `$NINA_CONFIG_DIR`. `config.yaml` only stores the *filename*
(`opencode.password_ref`) so the secret never lands in YAML. The file
itself is created with mode 0600 on POSIX systems.
"""

from __future__ import annotations

import os
import secrets
from pathlib import Path


def generate_password() -> str:
    """Return a 32-byte URL-safe password suitable for basic auth."""

    return secrets.token_urlsafe(32)


def password_path(config_dir: Path, ref: str) -> Path:
    """Resolve the password file path for a given config dir and ref name."""

    if not ref or ref != os.path.basename(ref):
        raise ValueError(f"opencode password_ref must be a filename, got {ref!r}")
    return config_dir / ref


def read_password(config_dir: Path, ref: str) -> str:
    """Read the password from disk. Raises FileNotFoundError if missing."""

    path = password_path(config_dir, ref)
    return path.read_text().strip()


def ensure_password_file(config_dir: Path, ref: str, force: bool = False) -> Path:
    """Create the password file if missing. Re-create when `force=True`.

    Returns the resolved path. The file is chmod 0600 on POSIX.
    """

    config_dir.mkdir(parents=True, exist_ok=True)
    path = password_path(config_dir, ref)
    if path.exists() and not force:
        return path
    path.write_text(generate_password())
    try:
        os.chmod(path, 0o600)
    except OSError:
        # Non-POSIX filesystem (e.g. Windows): best effort.
        pass
    return path
